# Generated by Django 3.2.17 on 2023-02-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='mesurement_unit',
            new_name='measurement_unit',
        ),
    ]
