# Generated by Django 3.2.17 on 2023-02-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_mesurement_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
