# Generated by Django 3.2.17 on 2023-02-25 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230225_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше 1 мин'), django.core.validators.MaxValueValidator(2000, 'Время приготовления не может быть больше 2000 мин')], verbose_name='Время приготовления, мин.'),
        ),
    ]
