# Generated by Django 3.2.17 on 2023-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_author'),
        ('users', '0002_auto_20230211_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite', to='recipes.Recipe'),
        ),
    ]
