# Generated by Django 3.2.17 on 2023-02-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_author'),
        ('users', '0003_customuser_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart', to='recipes.Recipe'),
        ),
    ]
